### ISSUE TITLE
Exception when setting global hotkey during handling of event in WPF

### ISSUE THREAD

**Issue by Ergwano** [thomaslevesque/NHotkey#19]
Hey,

I have a case in my application where I want to make a KeyBinding global or not global depending on a state in the application. So whenever a certain event is triggered I use `HotkeyManager.SetRegisterGlobalHotkey(...)` to enable/disable the KeyBinding being global. But if this happens in the same time when a KeyBinding is currently handled I get the following exception:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at NHotkey.Wpf.WeakReferenceCollection`1.<GetEnumerator>d__1.MoveNext() in C:\projects\nhotkey\src\NHotkey.Wpf\WeakReferenceCollection.cs:line 14
   at NHotkey.Wpf.HotkeyManager.ExecuteBoundCommand(Hotkey hotkey) in C:\projects\nhotkey\src\NHotkey.Wpf\HotkeyManager.cs:line 195
   at NHotkey.Wpf.HotkeyManager.HandleMessage(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled) in C:\projects\nhotkey\src\NHotkey.Wpf\HotkeyManager.cs:line 185
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by thomaslevesque** [comment]
Hi @Ergwano,

Thanks for reporting this!
It should be easy enough to fix, hopefully I should be able to do it in the next few days. Unless you want to take a shot at it?

**Comment by Ergwano** [comment]
Thanks for the fast answer. I actually already took a look at it and what resolved the issue for me, was copying the list before iterating through since locks didn't help because everything was running in one thread (https://github.com/Ergwano/NHotkey/commit/e9196b81488c62947a241a513a8af2c42076f8d0). If that's okay with you I'll create a pull request :)

**Comment by thomaslevesque** [comment]
Yeah, that's what I had in mind as well. Please go ahead with a PR!

**Comment by thomaslevesque** [comment]
The new packages have been pushed to NuGet, they should be available in a few minutes.
Thanks again @Ergwano!

**Comment by Ergwano** [comment]
Thank you very much @thomaslevesque!
